-- Milestone 3: Supabase / RAG database schema.
-- This migration creates storage for uploaded documents, chunks, and chat
-- history. Runtime ingestion, embeddings, and chat APIs are added later.

create schema if not exists extensions;

create extension if not exists vector
with
  schema extensions;

create table if not exists public.documents (
  id bigint generated by default as identity primary key,
  file_name text not null,
  file_type text not null,
  mime_type text,
  file_size_bytes integer not null check (file_size_bytes >= 0),
  text_length integer not null default 0 check (text_length >= 0),
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  constraint documents_file_type_check check (file_type in ('pdf', 'txt'))
);

create table if not exists public.document_chunks (
  id bigint generated by default as identity primary key,
  document_id bigint not null,
  chunk_index integer not null check (chunk_index >= 0),
  content text not null check (char_length(content) > 0),
  start_offset integer not null check (start_offset >= 0),
  end_offset integer not null check (end_offset >= start_offset),
  page_number integer check (page_number is null or page_number > 0),
  embedding extensions.vector(1536),
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamp with time zone not null default now(),
  constraint document_chunks_document_id_fkey foreign key (document_id)
    references public.documents (id)
    on delete cascade,
  constraint document_chunks_document_chunk_index_key unique (document_id, chunk_index)
);

create table if not exists public.chat_sessions (
  id bigint generated by default as identity primary key,
  title text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now()
);

create table if not exists public.chat_messages (
  id bigint generated by default as identity primary key,
  session_id bigint not null,
  role text not null,
  content text not null check (char_length(content) > 0),
  citations jsonb not null default '[]'::jsonb,
  created_at timestamp with time zone not null default now(),
  constraint chat_messages_session_id_fkey foreign key (session_id)
    references public.chat_sessions (id)
    on delete cascade,
  constraint chat_messages_role_check check (role in ('system', 'user', 'assistant'))
);

create index if not exists documents_created_at_idx
  on public.documents (created_at desc);

create index if not exists document_chunks_document_id_idx
  on public.document_chunks (document_id);

create index if not exists document_chunks_embedding_hnsw_idx
  on public.document_chunks
  using hnsw (embedding extensions.vector_cosine_ops)
  where embedding is not null;

create index if not exists chat_messages_session_created_at_idx
  on public.chat_messages (session_id, created_at);

alter table public.documents enable row level security;
alter table public.document_chunks enable row level security;
alter table public.chat_sessions enable row level security;
alter table public.chat_messages enable row level security;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists documents_set_updated_at on public.documents;
create trigger documents_set_updated_at
  before update on public.documents
  for each row
  execute function public.set_updated_at();

drop trigger if exists chat_sessions_set_updated_at on public.chat_sessions;
create trigger chat_sessions_set_updated_at
  before update on public.chat_sessions
  for each row
  execute function public.set_updated_at();

create or replace function public.match_document_chunks (
  query_embedding extensions.vector(1536),
  match_count integer default 5,
  match_threshold double precision default 0.0,
  filter_document_ids bigint[] default null
)
returns table (
  chunk_id bigint,
  document_id bigint,
  chunk_index integer,
  content text,
  page_number integer,
  start_offset integer,
  end_offset integer,
  file_name text,
  file_type text,
  similarity double precision,
  metadata jsonb
)
language sql
stable
as $$
  select
    dc.id as chunk_id,
    dc.document_id,
    dc.chunk_index,
    dc.content,
    dc.page_number,
    dc.start_offset,
    dc.end_offset,
    d.file_name,
    d.file_type,
    1 - (dc.embedding <=> query_embedding) as similarity,
    jsonb_build_object(
      'document', d.metadata,
      'chunk', dc.metadata
    ) as metadata
  from public.document_chunks dc
  join public.documents d on d.id = dc.document_id
  where dc.embedding is not null
    and (
      filter_document_ids is null
      or dc.document_id = any(filter_document_ids)
    )
    and 1 - (dc.embedding <=> query_embedding) >= coalesce(match_threshold, 0.0)
  order by dc.embedding <=> query_embedding
  limit least(greatest(coalesce(match_count, 5), 1), 50);
$$;

revoke execute
  on function public.match_document_chunks(
    extensions.vector,
    integer,
    double precision,
    bigint[]
  )
  from public, anon, authenticated;

grant execute
  on function public.match_document_chunks(
    extensions.vector,
    integer,
    double precision,
    bigint[]
  )
  to service_role;

comment on table public.documents is
  'Uploaded source documents for the document chat MVP.';

comment on table public.document_chunks is
  'Deterministic text chunks with optional pgvector embeddings for semantic retrieval.';

comment on table public.chat_sessions is
  'Chat conversations saved without user authentication in the MVP.';

comment on table public.chat_messages is
  'Messages and citation payloads for saved document-grounded answers.';

comment on function public.match_document_chunks is
  'Server-side vector similarity search over embedded document chunks.';
